# Generated by Django 5.0.7 on 2024-07-12 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NetworkConfigurationApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkinformation',
            name='date_assigned',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='networkinformation',
            name='p2p_secondary',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
