# Generated by Django 5.0.7 on 2024-07-12 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NetworkConfigurationApp', '0002_networkinformation_date_assigned_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkinformation',
            name='config_number',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
