# Generated by Django 5.0.7 on 2024-07-13 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NetworkConfigurationApp', '0004_alter_networkinformation_cpe_ip_range_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkinformation',
            name='approval_status',
            field=models.CharField(choices=[('APPROVED', 'APPROVED'), ('PENDING', 'PENDING'), ('DENIED', 'DENIED')], default='PENDING', max_length=20),
        ),
    ]
