# Generated by Django 5.0.7 on 2024-07-13 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NetworkConfigurationApp', '0005_networkinformation_approval_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='networkinformation',
            name='device_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NetworkConfigurationApp.devicegroup'),
        ),
    ]
