# Generated by Django 5.0.7 on 2024-07-13 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NetworkConfigurationApp', '0006_devicegroup_alter_networkinformation_device_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='DHCPCluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='networkinformation',
            name='dhcp_cluster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NetworkConfigurationApp.dhcpcluster'),
        ),
    ]
