# Generated by Django 5.0.7 on 2024-07-14 18:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NetworkConfigurationApp', '0007_dhcpcluster_alter_networkinformation_dhcp_cluster'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='networkinformation',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='networkinformation',
            name='cpe_netmask',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='networkinformation',
            name='cpe_subnet',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='networkinformation',
            name='date_recorded',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='networkinformation',
            name='mgmt_netmask',
            field=models.CharField(max_length=255),
        ),
    ]
